name: GetModel
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: curl -L "https://huggingface.co/bartowski/Phi-3-mini-4k-instruct-GGUF/resolve/main/Phi-3-mini-4k-instruct-v0.Q4_K_M.gguf" -o model.gguf
      - name: step2
        uses: actions/upload-artifact@v4
        with:
          name: phi3-model
          path: model.gguf
